{{- if and .Values.components.istio.enabled (eq .Values.solution.name "flux") }}
{{- $istioValues := .Values.components.istio }}
{{- $istiod := $istioValues.components.istiod }}
{{- if $istiod.create }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: {{ .Values.solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
spec:
  targetNamespace: {{ .Values.components.istio.namespace }}
  dependsOn:
    - name: istio-base
      namespace: {{ .Values.solution.namespace | quote }}
  chart:
    spec:
      chart: {{ $istioValues.components.istiod.chart.name }}
      version: {{ default $istioValues.chart.version $istiod.chart.version }}
      sourceRef:
        kind: {{ $istioValues.chart.source.kind }}
        name: {{ $istioValues.chart.source.repository }}
        namespace: {{ .Values.solution.namespace }}
  interval: {{ .Values.solution.interval }}
  values:
    {{- include "platform-system.components.istio.components.istiod.values" $ | nindent 4 }}
{{- end -}}
{{- end -}}
