{{ if and .Values.apps.istio.enabled (eq .Values.solution.name "flux") }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: istio-base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: {{ .Values.solution.interval }}
{{ end }}
