{{ if and (and .Values.apps.istio.enabled ) (eq .Values.solution.name "flux") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode:
    {{- if (eq .Values.apps.istio.mTLSMode "UNSET") }}
      {{- " UNSET" }}
    {{- else if (eq .Values.apps.istio.mTLSMode "DISABLE") }}
      {{- " DISABLE" }}
    {{- else if (eq .Values.apps.istio.mTLSMode "PERMISSIVE") }}
      {{- " PERMISSIVE" }}
    {{- else }}
      {{- " STRICT" }}
    {{- end }}
{{- end }}
