{{ if and (and .Values.apps.istio.enabled ) (eq .Values.solution.name "flux") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode:
    {{- if .Values.apps.istio.strictMTLS }}
      {{- " STRICT" }}
    {{- else }}
      {{- " DISABLE" }}
    {{- end }}
{{- end }}
