# Default values for platform-tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
# title formatted name of tenant
title: ""
# crdCheck for installed CRDS
crdCheck: true
# The target namespace for this tenant
targetNamespace:
  create: true
  name: ""
  labels: {}
  annotations: {}

commonAnnotations: {}
commonLabels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

components:
  # flux configs
  flux:
    namespace: flux-system
    source:
      create: true
      name: "ssh"
      url: ""
      # If a private repo, this is the secret for the GitRepository
      secretName: ""
      # defaults to
      # ref:
      #   branch: main
      ref: {}
    kustomization:
      enabled: true
      name: ""
      # any spec other than  `serviceAccountName` and `sourceRef`
      spec: {}

  rbac:
    enabled: true
    # Cluster role giving * access to flux resources
    tenantClusterRole:
      enabled: true
      name: ""
    # Role that gives tenant deployer access to the namespace
    tenantDeploymentRole:
      enabled: true
      name: ""
      extraRules: []
      # defaults to tenantDeploymentRole.name
      # group to map external objects to like IAM
      groupName: ""

  # using kyverno policies
  # to add labels/annotations on objects tenant deploys
  kyverno:
    enabled: true
    name: ""
    nodeSelector: {}
    tolerations: []
    labels: {}
    annotations: {}

  # If loki, prometheus and grafana installed
  # this configures a namespaced dashboard.
  o11y:
    enabled: true
    # namespace where prometheus resides
    namespace: o11y
    labels: {}
    annotations: {}

  # oauth2Proxy application to use for authentication
  oauth2Proxy:
    enabed: true
    # chart configuration for proxy app
    chart:
      url: https://oauth2-proxy.github.io/manifests
      name: oauth2-proxy
      version: "6.2.7"
    # displayName for sso redirect
    displayName: ""
    # oidcIssuerUrl of the OIDC provider for oauth proxy
    oidcIssuerUrl: ""
    # existingSecret has client-id, client-secret and cookie-secret keys
    existingSecret: ""
    # cookieDomain for proxy
    cookieDomain: ""
    # whitelistDomain for proxy
    whitelistDomain: ""
    # overrideValues for oauth2-proxy chart
    overrideValues: {}
  # apps:
  #   - name: "test-app-1"
  #     url: "testapp.domain"
  #     service:
  #       port: 8080
  #       host: myapp.testns.svc.cluster.local
  #   - name: "test-app-2"
  #     url: "testapp2.domain"
  #     service:
  #       port: 8080
  #       host: myapp2.testns.svc.cluster.local
  #     # "http" or "tls" or "tcp". Exclusion of 'mode' defaults to http
  #     mode: tls
  apps: []

  # certManager config will create certificates based on
  # tls credential names
  certManager:
    enabled: true
    issuerRef: {}

  # Use istio to manage networking
  istio:
    # enable all istio CR's
    enabled: true
    # namespace istio is installed in
    namespace: "istio-system"
