# Default values for platform-tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
# Formatted name of tenant
title: ""

# The target namespace for this tenant
targetNamespace:
  create: false
  name: ""
  labels: {}
  annotations: {}

commonAnnotations: {}
commonLabels: {}

serviceAccount:
  create: false
  name: ""
  annotations: {}

# flux configs
flux:
  namespace: flux-system
  source:
    create: false
    name: ""
    url: ""
    # If a private repo, this is the secret for the GitRepository
    secretName: ""
    # defaults to
    # ref:
    #   branch: main
    ref: {}
  kustomization:
    create: false
    name: ""
    # any spec other than  `serviceAccountName` and `sourceRef`
    spec: {}

rbac:
  enable: false
  # Cluster role giving * access to flux resources
  tenantClusterRole:
    create: true
    name: ""
  # Role that gives tenant deployer access to the namespace
  tenantDeploymentRole:
    create: true
    name: ""
    extraRules: []
    # defaults to tenantDeploymentRole.name
    # group to map external objects to like IAM
    groupName: ""

# using kyverno policies
# to add labels/annotations on objects tenant deploys
kyverno:
  enable: false
  name: ""
  nodeSelector: {}
  tolerations: []
  labels: {}
  annotations: {}

# If loki, prometheus and grafana installed
# this configures a namespaced dashboard.
observability:
  enable: false
  # namespace where prometheus resides
  namespace: observability
  labels: {}
  annotations: {}
