components:
  istio:
    name: istio
    enabled: true
    components:
      namespaceInjection:
        enabled: true
        name: namespace-injection
      # istioProxyQuit handles the kyverno policies for attaching an additional container
      # on job pods to kill the istio side car.
      # see https://github.com/skyfjell/istio-proxy-quit
      proxyQuit:
        # enabled flag for installing this component
        enabled: true
        name: proxy-quit
        image:
          registry: ghcr.io/skyfjell
          repository: istio-proxy-quit
          tag: 0.0.4
          pullPolicy: IfNotPresent
        sleepInterval: "5s"
        env: []
      kyverno:
        namespace: system-kyverno
  velero:
    name: velero
    namespace: system-velero
    # enabled set to false
    enabled: false
    components:
      backupPolicy:
        enabled: true
        # schedules for each namespace with
        # labels:
        #   skyfjell.io/backups: enabled
        #
        # namespaces can be customized on use case basis
        #  labels:
        #    skyfjell.io/backups-ignore: yearly
        #
        # the format is [resolution]: ttl in golang's time.ParseDuration format
        # to turn off set [resolution]: null
        schedules:
          hourly: 72h0m0s # 3 day ttl
          daily: 168h0m0s # week ttl
          weekly: 730h0m0s # month ttl
          monthly: 8760h0m0s # year ttl
        # additionalSchedules is an array with of values
        #
        # additionalSchedules:
        #   - name: kebab-name
        #     schedule: "* * * * 1"
        #     ttl: 3600
        #
        #  Can suppress additional schedules with
        #  labels:
        #    skyfjell.io/backups-ignore: kebab-name
        additionalSchedules: []
