{{- $parent := .Values.components.keycloak -}}
{{- $component := $parent.components.server -}}

{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}

{{- if and $parent.enabled $component.enabled .Values.components.certManager.enabled $istio.enabled $gateway.enabled -}}
{{- range $host := $parent.hosts }}
{{- $safename := regexReplaceAll "\\." $host "-" }}

{{- include "skyfjell.common.require.api.cert-manager.certificate" $ -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ list $parent.name $ | include "platform-auth.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
spec:
  secretName: {{ printf "%s-tls" (list $parent.name $safename $ | include "platform-auth.format.name" | trunc 59 ) }}
  dnsNames:
    - {{ $host }}
  {{- with $.Values.components.certManager.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end -}}
{{- end -}}