{{- if or .Values.components.keycloak.enabled .Values.components.privatebin.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: system-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    istio-injection: enabled
{{- end }}
