{{- if .Values.storage.minio.enabled }}
{{- $operatorTolerations := ( not .Values.storage.minio.operator.tolerations | ternary .Values.defaultTolerations.storage .Values.storage.minio.operator.tolerations ) }}
{{- $consoleTolerations := ( not .Values.storage.minio.console.tolerations | ternary .Values.defaultTolerations.apps .Values.storage.minio.console.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  releaseName: minio-operator
  chart:
    spec:
      chart: minio/minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio
  interval: 1h0m0s
  targetNamespace: minio-operator
  values:
    operator:
      tolerations: {{ toYaml $operatorTolerations | nindent 6 }}
    console:
      tolerations: {{ toYaml $consoleTolerations | nindent 6 }}
    tenants: []
{{- end }}
