{{- if .Values.storage.minio.enabled }}
{{- $tolerations := ( not .Values.storage.minio.tolerations | ternary .Values.defaultTolerations.storage .Values.storage.minio.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  releaseName: minio-operator
  chart:
    spec:
      chart: minio/minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio
  interval: 1h0m0s
  targetNamespace: minio-operator
  values:
    tolerations: {{ toYaml $tolerations | nindent 6 }}
{{- end }}
