crdCheck: false

targetNamespace:
  name: my-app

components:
  rbac:
    enabled: true

  kyverno:
    enabled: true

  o11y:
    enabled: true

  istio:
    enabled: true
  certManager:
    enabled: true
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io

  oauth2Proxy:
    enabled: true
    displayName: "Login With Keycloak"
    oidcIssuerUrl: "my.domain"
    existingSecret: "super-secret"
    cookieDomain: ".tentant1.domain"
  apps:
    - name: "test-app-1"
      host: "webapp1.tentant1.domain"
      service:
        port: 8080
        host: myapp.testns.svc.cluster.local
      routingOverride:
        http:
          - match:
              - uri:
                  prefix: /
            route:
              - destination:
                port:
                  number: 3

      # mode: "http" or "tls" or "tcp". Omissions defaults to http
    - name: "test-app-2"
      host: "webapp2.tentant1.domain"
      service:
        port: 8080
        host: myapp2.testns.svc.cluster.local
      mode: tls
