components:
  rbac:
    enabled: true

  kyverno:
    enabled: true

  o11y:
    enabled: true

  istio:
    enabled: true
  certManager:
    enabled: true
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io

  oauth2Proxy:
    enabled: true
    displayName: "Login With Keycloak"
    oidcIssuerUrl: "sso.example.com"
    existingSecret: "super-secret"
    cookieDomain: ".tenant.example.com"
  apps:
    - name: "test-app-1"
      host: "tenant.example.com"
      service:
        port: 8080
        host: test-app-1.tenant.svc.cluster.local
      routingOverride:
        http:
          - match:
              - uri:
                  prefix: /
            route:
              - destination:
                port:
                  number: 3

      # mode: "http" or "tls" or "tcp". Omissions defaults to http
    - name: "test-app-2"
      host: "test-app-2.tenant.example.com"
      service:
        port: 8080
        host: test-app-2.tenant.svc.cluster.local
      mode: tls
