{{ if and .Values.components.externalDns.enabled (eq .Values.solution.name "flux") }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: {{ .Values.components.externalDns.namespace }}
  chart:
    spec:
      chart: external-dns
      version: {{ .Values.components.externalDns.version }}
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: {{ .Values.solution.interval }}
  values:
    {{- include "platformSystem.helper.annotations" (list "externalDns" $) | indent 4 }}
    {{- include "platformSystem.helper.nodeSelector" (list "externalDns" $) | indent 4 }}
    {{- include "platformSystem.helper.tolerations" (list "externalDns" $) | indent 4 }}
    {{- with .Values.components.externalDns.serviceAccountAnnotations }}
    serviceAccount:
      annotations: {{- toYaml . | nindent 8 }}
    {{- end }}
    global:
      enabled: false
      name: external-dns
    server:
      enabled: true
      replicas: 1
      boostrapExpect: 1
    podSecurityContext:
      fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
{{ end }}


