{{ if and .Values.components.minioOperator.enabled (eq .Values.solution.name "flux") }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: {{ .Values.solution.namespace | quote }}
spec:
  url: https://operator.min.io
  interval: 10m
{{ end }}
