{{ if and .Values.components.istio.enabled (eq .Values.solution.name "flux") }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 10m
{{ end }}