{{ if and .Values.components.externalDns.enabled (eq .Values.solution.name "flux") }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: {{ .Values.solution.namespace | quote }}
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
{{ end }}
