{{ if and .Values.components.kyverno.enabled (eq .Values.solution.name "flux") }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  url: https://kyverno.github.io/kyverno
  interval: 10m
{{ end }}
