{{- if .Values.services.velero.enabled  }}
{{- $tolerations := ( not .Values.services.velero.tolerations | ternary $.Values.services.tolerations.services .Values.services.velero.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware
  interval: 1h0m0s
  targetNamespace: velero
  values:
    tolerations: {{ toYaml $tolerations | nindent 6 }}
    {{ toYaml .Values.services.velero.values | nindent 4 }}
{{- end }}
