{{- if and .Values.components.rbac.enabled .Values.components.rbac.components.tenantClusterRole.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ list . | include "platform-tenant.format.name.shared" }}
  name: {{ list . | include "platform-tenant.format.name.shared" }}
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["*"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["helmrepositories", "gitrepositories"]
    verbs: ["*"]
{{- end -}}
