{{- if .Values.components.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ list .Values.components.serviceAccount.name . | include "platform-tenant.format.name.shared" }}
  namespace: {{ .Values.components.flux.namespace }}
{{- if or .Values.components.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.components.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
