# Use Mozilla SOPS or something of the like for committing secrets to git in production.
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pg
  namespace: auth-keycloak
stringData:
  password: p@ssw0rd
  username: keycloak
  postgres-password: "@dmin-p@ssw0rd"
