# Use Mozilla SOPS or something of the like for committing secrets to git in production.
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: auth-keycloak
stringData:
  password: admin-password
  username: admin
