components:
  certManager:
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io
  keycloak:
    enabled: true
    host: sso.example.com
    components:
      server:
        admin:
          usernameSecretRef:
            name: keycloak-admin
            key: username
          passwordSecretRef:
            name: keycloak-admin
            key: password
      database:
        enabled: true
        auth:
          existingSecret: "secret-pg"
global:
  tolerations:
    - key: example-key
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    "kubernetes.io/os": "linux"
