{{- if .Values.services.velero.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vmware
  namespace: flux-system
spec:
  url: https://vmware-tanzu.github.io/helm-charts
  interval: 10m
{{- end }}
