apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: {{ .Values.domain }}
  dnsNames:
    - "*.{{ .Values.domain }}"
    - {{ .Values.domain }}
