apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@omniteq.com
    privateKeySecretRef:
      name: ingress-certs
    solvers:
      - dns01:
          route53:
            region: us-east-2
        selector:
          dnsZones:
            - {{ .Values.domain }}