{{- if .Values.services.certManager.enabled  }}
{{- $tolerations := ( not .Values.services.certManager.tolerations | ternary .Values.services.tolerations .Values.services.certManager.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1h0m0s
  targetNamespace: cert-manager
  values:
    installCRDs: true
    tolerations: {{ toYaml $tolerations | nindent 8 }}
    webhook:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
    cainjector:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
    startupapicheck:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
{{- end }}
