# The namespace to target for all HelmReleases
namespace: istio-system

helmRepository:
  # creates the flux helmrepository CR
  create: true
  # namespace to create the CR in
  namespace: flux-system
  # name of CR
  name: istio
  # refresh interval
  interval: 10m

helmRelease:
  # the namespace where the HelmRelease CR is installed to
  releaseNamespace: flux-system
  enabled: true
  # istio base chart release
  base:
    # Installs the base chart via HelmRelease. The base chart
    # installs CRDs and RBAC
    enabled: true
    # HelmRelease CR name
    name: istio-base
    # Helm chart version
    version: "1.15.1"
    # HelmRelease interval
    interval: "1h0m0s"
    # CRD policies
    # override defaults
    crds:
      install: Create
      update: CreateReplace
    # Override HelmRelease values
    values: {}
