---
{{- if .Values.services.vault.enabled  }}
{{- $tolerations := $.Values.services.tolerations.services }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  releaseName: secrets-store-csi-driver
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  interval: 1h0m0s
  targetNamespace: kube-system
  values:
    linux:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
{{- end }}
