{{- if .Values.components.keycloak.enabled  }}
{{- $tolerations := ( not .Values.components.keycloak.tolerations | ternary .Values.components.tolerations .Values.components.keycloak.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1h0m0s
  targetNamespace: system-auth
  values:
    auth:
      createAdminUser: false
    proxyAddressForwarding: true
    postgresql:
      enabled: false
    externalDatabase:
      host: system-auth-postgresql

    tolerations: {{ toYaml $tolerations | nindent 6 }}
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: StatefulSet
            apiVersion: apps/v1
            metadata:
              name: keycloak
              namespace: system-auth
            spec:
              template:
                spec:
                  containers:
                    - name: keycloak
                      env:
                        - name: KEYCLOAK_DATABASE_USER
                          valueFrom:
                            secretKeyRef:
                              name: keycloak-vault-postgresql
                              key: username
                        - name: KEYCLOAK_DATABASE_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: keycloak-vault-postgresql
                              key: password
                      volumeMounts:
                        - name: keycloak-vault-postgresql
                          mountPath: /mnt/secrets-store/postgresql
                          readOnly: true
                  volumes:
                    - name: keycloak-vault-postgresql
                      csi:
                        driver: secrets-store.csi.k8s.io
                        readOnly: true
                        volumeAttributes:
                          secretProviderClass: keycloak-vault-postgresql
{{- end }}
