{{- $istio := .Values.components.istio -}}
{{- $apps := .Values.components.apps -}}
{{- $gateway := $istio.components.gateway -}}
{{- if and $istio.enabled $gateway.enabled -}}
{{- range $apps -}}
{{- include "skyfjell.common.require.api.istio.authorization-policy" $ -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ list .name "gateway" "http" $ | include "platform-factory.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
    skyfjell.io/from: {{ list .host "http" | include "skyfjell.common.format.name" }}
    skyfjell.io/to-ns: {{ $gateway.namespace }}
    skyfjell.io/to: {{ list $gateway.name "http" | include "skyfjell.common.format.name" }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      {{- $selector := $gateway.selector }}
      {{- if $selector }}
      {{- $selector | toYaml | nindent 6 }}
      {{- else }}
      app: {{ $istio.components.gateway.name }}
      {{- end }}
  rules:
    - to:
        - operation:
            hosts:
              - {{ .host }}
            ports:
              - "80"
              - "443"
{{- end -}}
{{- end -}}