{{- $istio := .Values.components.istio -}}
{{- $apps := .Values.components.apps -}}
{{- $gateway := $istio.components.gateway -}}
{{- if and $apps $istio.enabled -}}
{{- range $apps -}}
{{- include "skyfjell.common.require.api.istio.vs" $ -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
spec:
  hosts:
    - {{ .host }}
  gateways:
    - {{ list .name $ | include "platform-factory.format.name" | printf "%s/%s" $gateway.namespace }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ .service.port }}
            host: {{ .service.host }}
{{- end -}}
{{- end -}}