{{- $component := .Values.components.kyverno -}}
{{- $solution := .Values.solution -}}

{{- $repo := .Values.components.helmRepositories.components.kyverno -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}
---
{{- if and $component.enabled (eq $solution.name "flux") }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ list $component.name $ | include "platform-system.format.name" }}
  namespace: {{ $solution.namespace | quote }}
spec:
  releaseName: {{ list $component.name $ | include "platform-system.format.name" }}
  targetNamespace: {{ list $component . | include "skyfjell.common.format.component.namespace" }}
  chart:
    spec:
      chart: kyverno
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ $solution.namespace | quote }}
  interval: {{ $solution.interval }}
  values:
{{- $defaultValues := ( include "platform-system.components.kyverno.defaultValues" $ | fromYaml ) }}
{{ mergeOverwrite $defaultValues $component.values | toYaml | indent 4 }}
{{- end }}
