{{- if and .Values.keycloak.enabled .Values.keycloak.release.chart.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: {{ .Release.Name }}-codecentric
  namespace: {{ .Values.fluxNamespace }}
spec:
  url: https://codecentric.github.io/helm-charts
  interval: 10m
{{- end }}