# `and` condition any other auth services as needed.
{{- if or .Values.apps.keycloak.enabled .Values.apps.privatebin.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: auth-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: ingress-cert
      # Concat any other auth service hosts as needed.
      hosts: 
        {{- toYaml .Values.apps.keycloak.hosts | indent 8 }}
        {{- toYaml .Values.apps.privatebin.hosts | indent 8 }}
{{- end }}
