{{- $component := .Values.components.privatebin -}}
{{- $istio := .Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}

{{- if and $component.host $istio.enabled $gateway.enabled -}}
{{- include "skyfjell.common.require.api.istio.authorization-policy" $ -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ list $component.name "gateway" "http" $ | include "platform-factory.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
    skyfjell.io/from: {{ list $component.host "http" | include "skyfjell.common.format.name" }}
    skyfjell.io/to-ns: {{ $gateway.namespace }}
    skyfjell.io/to: {{ list $gateway.name "http" | include "skyfjell.common.format.name" }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      {{- $selector := $gateway.selector }}
      {{- if $selector }}
      {{- $selector | toYaml | nindent 6 }}
      {{- else }}
      app: {{ $istio.components.gateway.name }}
      {{- end }}
  rules:
    - to:
        - operation:
            hosts:
              - {{ $component.host }}
            ports:
              - "80"
              - "443"
{{- end -}}
