global:
  tolerations:
    - key: values
  nodeSelector:
    "skyfjell.io/node-selector": "platform-system"
components:
  istio:
    components:
      gateway:
        enabled: true
  velero:
    components:
      server:
        serviceAccountAnnotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::XXXXXXXXXXXX:role/velero"
        provider:
          name: aws
          bucket: "velero-s3-123213213213"
          region: "us-east-2"
          kmsKeyId: "alias/my-kms-id"
