{{ $component := .Values.components.traefik }}

{{- if $component.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ list $component.namespace . | include "platform-auth.format.name" }}
{{- end -}}
