{{ $component := .Values.components.keycloak }}
{{ $name := list $component.name $ | include "platform-auth.format.name" }}
{{ $dbName := list $component.name $component.components.database.name $ | include "platform-auth.format.name" }}
{{- if and $component.enabled  }}
{{- if .Values.crdCheck }}
  {{- include "require.api.flux.helmRelease" . -}}
{{- end -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Values.components.flux.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}    
spec:
  targetNamespace: {{ $component.namespace }}
  {{- if $component.components.database.enabled }}
  dependsOn:
    - name: {{ $dbName }}
      namespace: {{ .Values.components.flux.namespace }}
  {{- end }}
  chart:
    spec:
      chart: {{ $component.chart.name }}
      {{- with $component.chart.version  }}
      version: {{ . }}
      {{- end }}
      sourceRef:
        kind: HelmRepository
        name: {{ list "codecentric" $ | include "platform-auth.format.name" }}
        namespace: {{ .Values.components.flux.namespace }}
  interval: 1h0m0s
  values:
{{- $defaultValues := ( include "platform-auth.components.keycloak.values" $ | fromYaml ) }}
{{ ( mergeOverwrite $defaultValues (default dict $component.valuesOverride )) | toYaml | indent 4 }}
{{- end }}