{{ $component := .Values.components.keycloak.components.database }}
{{ $parentComponent := .Values.components.keycloak }}
{{ $name := list $parentComponent $component $ | include "platform-auth.format.name" }}
{{- if and $component.enabled $parentComponent.enabled }}
  {{- if .Values.crdCheck }}
    {{- include "require.api.flux.helmRelease" . -}}
  {{- end }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Values.components.flux.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
spec:
  targetNamespace: {{ .Values.components.keycloak.namespace }}
  chart:
    spec:
      chart: {{ $component.chart.name }}
      {{- with $component.chart.version }}
      version: {{ . }}
      {{- end }}
      sourceRef:
        kind: HelmRepository
        name: {{ list "bitnami" $ | include "platform-auth.format.name" }}
        namespace: {{ .Values.components.flux.namespace }}
  interval: 1h0m0s
  values:
{{- $defaultValues := ( include "platform-auth.components.keycloak.components.database.values" $ | fromYaml ) }}
{{ ( mergeOverwrite $defaultValues (default dict .Values.components.keycloak.components.database.valuesOverride )) | toYaml | indent 4 }}
{{- end -}}
