# Default values for platform-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterIssuerName: ""
fluxNamespace: "flux-system"
nodeSelector: {}
tolerations: []

keycloak:
  enabled: true
  admin:
    username: "admin"
    # usernameSecretRef:
    #   name: ""
    #   key: ""
    # don't use me in production
    # password: "asd"
    # passwordSecretRef:
    #   name: ""
    #   key: ""
  release:
    chart:
      # Will install the built in helm repository.
      enabled: true
      name: "keycloakx"
      version: "1.6.0"
    values:
      fullnameOverride: keycloak
      nodeSelector:
        skyfjell.io/node-selector: platform-services
      command:
        - "/opt/keycloak/bin/kc.sh"
        - "--verbose"
        - "start"
        - "--auto-build"
        - "--http-enabled=true"
        - "--http-port=8080"
        - "--hostname-strict=false"
        - "--hostname-strict-https=false"
        - "--spi-events-listener-jboss-logging-success-level=info"
        - "--spi-events-listener-jboss-logging-error-level=warn"
      dbchecker:
        enabled: true
      database:
        existingSecret: "auth-pguser-keycloak"
        vendor: postgres
        hostname: "auth-primary"
        port: "5432"
        username: "keycloak"
  cert:
    enabled: true
    dnsNames: []
    # can override with different cluster issuer
    # clusterIssuerName: ""
  gateway:
    enabled: true
    istioNamespace: ""

    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
