# Default values for platform-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# crdCheck for installed CRDS
crdCheck: true

commonAnnotations: {}
commonLabels: {}
nodeSelector: {}
tolerations: []

components:
  # flux configs
  flux:
    enabled: true # will break without but testing
    # namespace of flux
    namespace: flux-system
  # istio configs
  istio:
    # enabled istio injections and networkings
    enabled: true
    # namespace of istio
    namespace: "istio-system"
  # certManager configs
  certManager:
    # enabled cert-manager components
    enabled: true
    # issuerRef to create cert
    issuerRef: {}
  keycloak:
    enabled: true
    # namespace to deploy the keycloak helm release into
    namespace: "keycloak"
    admin:
      username: "admin"
      # usernameSecretRef:
      #   name: ""
      #   key: ""
      # don't use me in production
      # password: "asd"
      # passwordSecretRef:
      #   name: ""
      #   key: ""
    # chart source config
    chart:
      url: "https://codecentric.github.io/helm-charts"
      name: "keycloakx"
      version: "1.6.0"
    valuesOverride: {}
    # storage configuration for keycloak
    storage:
      enabled: true
      # chart source of storage. Currently only bitnami postgres or bitnami postgres-ha are supported for easy config.
      chart:
        url: https://charts.bitnami.com/bitnami
        name: postgres # can be postgres-ha
        version: "12.1.2"
      valuesOverride: {}

  traefik:
    enabled: true
    namespace: traefik
    chart:
      url: "https://traefik.github.io/charts"
      name: "traefik"
      version: "20.1.1"
# keycloak:
#   release:
#     chart:
#       # Will install the built in helm repository.
#       enabled: true
#       name: "keycloakx"
#       version: "1.6.0"
#     values:
#       fullnameOverride: keycloak
#       nodeSelector:
#         skyfjell.io/node-selector: platform-services
#       command:
#         - "/opt/keycloak/bin/kc.sh"
#         - "--verbose"
#         - "start"
#         - "--auto-build"
#         - "--http-enabled=true"
#         - "--http-port=8080"
#         - "--hostname-strict=false"
#         - "--hostname-strict-https=false"
#         - "--spi-events-listener-jboss-logging-success-level=info"
#         - "--spi-events-listener-jboss-logging-error-level=warn"
#       dbchecker:
#         enabled: true
#       database:
#         existingSecret: "auth-pguser-keycloak"
#         vendor: postgres
#         hostname: "auth-primary"
#         port: "5432"
#         username: "keycloak"
#   cert:
#     enabled: true
#     dnsNames: []
#     # can override with different cluster issuer
#     # clusterIssuerName: ""
#   gateway:
#     enabled: true
#     istioNamespace: ""

#  - secretName: chart-example-tls
#    hosts:
#      - chart-example.local
