{{ $component := .Values.components.config }}

{{- $istio := .Values.components.istio -}}

{{- $repo := .Values.components.helmRepositories.components.skyfjell -}}
{{- $sourceName := list $repo.name $ | include "platform-system.format.name" -}}
{{- $sourceName := default $sourceName $component.chart.source.name -}}

{{ if eq .Values.solution.name "flux" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: platform-system-config
  namespace: {{ .Values.solution.namespace | quote }}
  labels:
    {{- include "platform-system.labels" $ | nindent 4 }}
spec:
  targetNamespace: {{ .Values.components.istio.namespace }}
  dependsOn:
    - name: {{ list $istio.name $istio.components.base.name $ | include "platform-system.format.name" }}
      namespace: {{ .Values.solution.namespace | quote }}
  chart:
    spec:
      chart: platform-system-config
      version: {{ $component.chart.version }}
      sourceRef:
        kind: {{ $component.chart.source.kind }}
        name: {{ $sourceName }}
        namespace: {{ default .Values.solution.namespace $repo.namespace }}
  interval: {{ .Values.solution.interval }}
  values: {{ toYaml .Values | nindent 4 }}
{{- end -}}
