{{ if .Values.apps.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode: {{ .Values.apps.istio.mTLSMode | default "STRICT" | quote }}
{{- end }}
