{{ if .Values.services.istio.enabled }}
{{- $tolerations := ( not .Values.services.istio.tolerations | ternary .Values.services.tolerations .Values.services.istio.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-install
  namespace: flux-system
spec:
  releaseName: istio-install
  chart:
    spec:
      chart: istio-install
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
  values:
    tolerations: {{ toYaml $tolerations | nindent 6 }}
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-operator
{{ end }}
