{{- if and .Values.components.rbac.enable .Values.components.rbac.components.tenantClusterRole.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helper.clusterRoleName" .}}
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["*"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["helmrepositories", "gitrepositories"]
    verbs: ["*"]
{{- end -}}