{{- if and .Values.components.rbac.enabled .Values.components.rbac.tenantClusterRole.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "platform-tenant.cluster-role.name" .}}
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["*"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["helmrepositories", "gitrepositories"]
    verbs: ["*"]
{{- end -}}