{{- if .Values.rbac.enable -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ default (include "platform-tenant.fullname" .) .Values.targetNamespace.name }}
  name: {{ include "helper.deployerRoleName" .}}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
    {{- if .Values.flux.kustomization.create }}
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomization"]
    resourceNames: 
      - {{ default (include "platform-tenant.fullname" .) .Values.flux.kustomization.name }}
    verbs:
      - get
    {{- end }}
  {{- with .Values.rbac.extraRules }}
    {{- toYaml . | nindent 2}}
  {{- end }}
{{- end -}}