{{- if and .Values.rbac.enabled .Values.flux.kustomization.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.flux.namespace }}
  name: {{ printf "%s-%s" .Release.Name "flux-ro" | trunc 63 | trimSuffix "-" | quote}}
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomization"]
    resourceNames: 
      - {{ default (include "platform-tenant.fullname" .) .Values.flux.kustomization.name }}
    verbs:
      - get
{{- end -}}