{{- if .Values.components.certManager.enabled -}}
  {{- if ( and .Values.crdCheck .Values.components.apps ) -}}
    {{ include "require.api.certManager.certificate" $ }}
  {{- end -}}
{{ range .Values.components.apps }}
---
{{ include "platform-tenant.app.certificate.template" (list . $) }}
{{- end -}}
{{- end -}}