{{- if .Values.certManager.enabled -}}
  {{- if ( and .Values.crdCheck .Values.appAuth.apps ) -}}
    {{ include "require.api.certManager.certificate" $ }}
  {{- end -}}
{{ range .Values.appAuth.apps }}
---
{{ include "platform-tenant.app.certificate" (list . $) }}
{{- end -}}
{{- end -}}