{{ if .Values.istio.certManager.createCerts }}
  {{ if .Values.crdCheck }}
  {{ include "require.api.certManager.certificate" $ }}
  {{ end }}
  {{ range $val := (.Values.istio.gateway ).servers }}
    {{ include "certManager.certificate" (list $val $) }}
  {{ end }}
{{ end }}