{{ if .Values.components.certManager.enabled}}
  {{ include "require.api.certManager.certificate" $}}
  {{ range $val := (.Values.components.istio.gateway ).servers }}
    {{ include "certManager.certificate" (list $val $)}}
  {{ end }}
{{ end }}