{{- if .Values.components.istio.enable -}}
{{ include "require.api.istio.gateway" $}}
{{ with .Values.components.istio.gateway }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ printf "%s-gateway" (include "platform-tenant.fullname" $)  }}
  namespace: {{ $.Values.components.istio.namespace  }}
spec:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}