{{- if .Values.istio.enable -}}
{{ with .Values.istio.gateway }}
{{- include "require.api.istio.gateway" . -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ printf "%s-gateway" (include "platform-tenant.fullname" $)  }}
  namespace: {{ $.Values.istio.namespace  }}
spec:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}