{{- if .Values.istio.enabled -}}
  {{- if ( and .Values.crdCheck .Values.appAuth.apps ) -}}
    {{ include "require.api.istio.gateway" $ }}
  {{- end -}}
{{ range .Values.appAuth.apps }}
---
{{ include "platform-tenant.app.gateway" (list . $) }}
{{- end -}}
{{- end -}}