{{- if .Values.components.istio.enabled -}}
  {{- if ( and .Values.crdCheck .Values.components.apps ) -}}
    {{ include "require.api.istio.gateway" $ }}
  {{- end -}}
{{ range .Values.components.apps }}
---
{{ include "platform-tenant.app.gateway.template" (list . $) }}
{{- end -}}
{{- end -}}