{{- if .Values.kyverno.enable -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ default (include "platform-tenant.fullname" .) .Values.kyverno.name }}
  annotations:
    policies.kyverno.io/title: {{ default (include "platform-tenant.fullname" .) .Values.kyverno.name }} policy 
    policies.kyverno.io/category: Pod Scheduling
    policies.kyverno.io/description: >-
      Adds metadata to all jobs, deployments, daemons etc in the monitoring
      namespace.
spec:
  validationFailureAction: enforce
  rules:
    - name: add-metadata
      match:
        resources:
          kinds:
            - Job
            - DaemonSet
            - Deployment
            - StatefulSet
            - ReplicaSet
          namespaces:
            - {{ default (include "platform-tenant.fullname" .) .Values.targetNamespace.name }}
      mutate:
        patchStrategicMerge:
          metadata:
          {{- with .Values.kyverno.annotations }}
            annotations:
              {{- toYaml . | nindent 14 }}
          {{- end }}          
            labels:
              app.kubernetes.io/part-of: {{ (include "platform-tenant.fullname" .) | quote }}
              {{- with (omit .Values.kyverno.labels "app.kubernetes.io/part-of") }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
          spec:
            template:
              {{- if or .Values.kyverno.nodeSelector .Values.kyverno.tolerations }}
              spec:
              {{- with .Values.kyverno.nodeSelector }}
                nodeSelector:
                  {{- toYaml . | nindent 18 }}
              {{- end }}
              {{- with .Values.kyverno.tolerations }}
                tolerations:
                  {{- toYaml . | nindent 18}}
              {{- end }}
              {{- else }}
              spec: {}
              {{- end }}
{{- end -}}