{{- if .Values.components.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "platform-tenant.fullname" .) .Values.components.serviceAccount.name }}
  namespace: {{ .Values.components.flux.namespace }}
{{- if or .Values.components.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.components.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}