{{- $apps := omit .Values.components "certManager" "istio" -}}
{{- range (keys $apps | sortAlpha) -}}
{{- $app := get $apps . -}}
{{- $istio := $.Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}
{{- if and $app.host $istio.enabled $gateway.enabled -}}
{{- include "skyfjell.common.require.api.istio.authorization-policy" $ -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ list $gateway.namespace $gateway.name $app.namespace $app.name | include "skyfjell.common.format.name" }}
  namespace: {{ $app.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
    {{- include "platform-app-config.labels" $ | nindent 4 }}
    skyfjell.io/from-ns: {{ $gateway.namespace }}
    skyfjell.io/from: {{ $gateway.name }}
    skyfjell.io/to-ns: {{ $app.namespace }}
    skyfjell.io/to: {{ $app.name }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $app.name }}
      app.kubernetes.io/instance: {{ list $app.name $ | include "platform-app-config.format.name" }}
  rules:
    - from:
      - source:
          namespaces:
            - {{ $gateway.namespace }}
          principals:
            - {{ printf "cluster.local/ns/%s/sa/%s" $gateway.namespace $gateway.name }}
      to:
        - operation:
            hosts:
              - {{ $app.host }}
{{- end -}}
{{- end -}}