{{- $apps := omit .Values.components "certManager" "istio" -}}
{{- $istio := $.Values.components.istio -}}
{{- $gateway := $istio.components.gateway -}}
{{- range (keys $apps | sortAlpha) -}}
{{- $app := get $apps . -}}
{{- if and $app.host $.Values.components.certManager.enabled $istio.enabled $gateway.enabled -}}
{{- include "skyfjell.common.require.api.istio.gateway" $ -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ list $app.name $ | include "platform-app-config.format.name" }}
  namespace: {{ $gateway.namespace }}
  labels: {{- include "skyfjell.common.chartLabels" $ | nindent 4 }}
  {{- include "platform-app-config.labels" $ | nindent 4 }}
spec:
  selector:
    {{- $selector := $gateway.selector | default $gateway.selector }}
    {{- if $selector }}
    {{- $selector | toYaml | nindent 4 }}
    {{- else }}
    app: {{ $gateway.name }}
    {{- end }}
  servers:
    - hosts:
        - {{ $app.host }}
      port:
        name: http2
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - {{ $app.host }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ $app.host }}
      {{- if and $.Values.components.certManager.enabled $.Values.components.certManager.issuerRef }}
      tls:
        mode: SIMPLE
        credentialName: {{ printf "%s-tls" ( list $app.name $app.namespace $ | include "platform-app-config.format.name" ) }}
      {{- end }}
{{- end -}}
{{- end -}}
