{{- if .Values.services.vault.enabled  }}
{{- $tolerations := ( not .Values.services.vault.tolerations | ternary $.Values.defaultTolerations.services .Values.services.vault.tolerations ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 1h0m0s
  targetNamespace: vault
  values:
    injector:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
    server:
      tolerations: {{ toYaml $tolerations | nindent 8 }}
{{- end }}
