name: Test Charts

on:
  pull_request:
    branches: [main]

jobs:
  test-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Iterate over Charts
        env:
          # csv
          IGNORE_FOLDERS: "common,platform-system-config"
        run: |
          set -f
          ignores=(${IGNORE_FOLDERS//,/ })

          for i in $(ls charts);
          do
            if [[ " ${ignores[*]} " =~ " ${i} " ]];
            then
              echo "::notice title=Ignore:: Skipping $i chart"
            else
                cd charts/$i
                helm repo add skyfjell https://charts.skyfjell.io
                helm dependency update
                echo "Testing $i chart"
                helm template --dry-run --debug test . --set crdCheck=false -f examples/values.test.yaml
                cd ../..
            fi
          done
