name: Test Charts

on:
  pull_request:
    branches: [main]

jobs:
  list-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        env:
          # csv
          IGNORE_FOLDERS: |
            common
            platform-system-config
        run: |
          array1=$(echo $IGNORE_FOLDERS | jq -R -s 'split("\n") -[""]')
          array2=$(ls | jq -R -s 'split("\n") -[""]')
          array_diff=$(jq -n --argjson array1 "$array1" --argjson array2 "$array2" 
          '{"all": $array2,"some":$array1} | .all-.some' )
          echo "CHARTS=$array_diff" >> $GITHUB_OUTPUT
  test-charts:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        manifest: ${{ fromJson(needs.list-manifests.outputs.CHARTS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Setup Deps
        working-directory: ${{ matrix.manifest }}
        run: |
          helm repo add skyfjell https://charts.skyfjell.io
          helm dependency update
      - name: Test ${{ matrix.manifest }} Examples
        working-directory: ${{ matrix.manifest }}
        run: |
          helm template --dry-run --debug test-auth . --set crdCheck=false -f examples/values.yaml
