name: Test Release

on:
  pull_request:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - uses: AbsaOSS/k3d-action@v2
        name: "Create Single Cluster"
        with:
          cluster-name: "test-platform-system"
          args: >-
            --no-lb
            --agents 1
            --k3s-arg "--disable=traefik@server:0"
      - name: Install Dependencies
        run: |
          helm repo add skyfjell https://charts.skyfjell.io
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux install
      - name: Test Platform System
        working-directory: charts/platform-system
        run: |
          helm dependency update
          helm install --wait --debug system . -f examples/values.test.yaml
      - name: Test Platform Auth
        working-directory: charts/platform-auth
        run: |
          helm dependency update
          helm install --wait --debug auth . -f examples/values.test.yaml
